// <auto-generated />
using Brasserie.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Brasserie.Data.Migrations
{
    [DbContext(typeof(BrasserieContext))]
    [Migration("20200510175758_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Brasserie.Core.Domain.Biere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrasserieId")
                        .HasColumnType("int");

                    b.Property<double>("DegreAlcool")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BrasserieId");

                    b.ToTable("Biere");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrasserieId = 1,
                            DegreAlcool = 6.5999999999999996,
                            Nom = "Leffe Blonde",
                            Prix = 2.2000000000000002
                        },
                        new
                        {
                            Id = 2,
                            BrasserieId = 1,
                            DegreAlcool = 7.5999999999999996,
                            Nom = "Leffe Brune",
                            Prix = 2.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            BrasserieId = 2,
                            DegreAlcool = 6.5999999999999996,
                            Nom = "Chimay Bleue",
                            Prix = 3.3999999999999999
                        },
                        new
                        {
                            Id = 4,
                            BrasserieId = 2,
                            DegreAlcool = 6.5999999999999996,
                            Nom = "Chimay Blonde",
                            Prix = 3.2000000000000002
                        },
                        new
                        {
                            Id = 5,
                            BrasserieId = 2,
                            DegreAlcool = 8.0,
                            Nom = "Chimay Rouge",
                            Prix = 3.0
                        });
                });

            modelBuilder.Entity("Brasserie.Core.Domain.Brasserie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brasseries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Abbaye de Leffe"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Abbaye de Chimay"
                        });
                });

            modelBuilder.Entity("Brasserie.Core.Domain.Grossiste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grossiste");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "GeneDrinks"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Onidrinks"
                        });
                });

            modelBuilder.Entity("Brasserie.Core.Domain.StockGrossiste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BiereId")
                        .HasColumnType("int");

                    b.Property<int>("GrossisteId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BiereId");

                    b.HasIndex("GrossisteId");

                    b.ToTable("StockGrossiste");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BiereId = 1,
                            GrossisteId = 1,
                            Quantite = 10
                        },
                        new
                        {
                            Id = 2,
                            BiereId = 2,
                            GrossisteId = 1,
                            Quantite = 15
                        },
                        new
                        {
                            Id = 3,
                            BiereId = 3,
                            GrossisteId = 1,
                            Quantite = 10
                        },
                        new
                        {
                            Id = 4,
                            BiereId = 4,
                            GrossisteId = 1,
                            Quantite = 5
                        },
                        new
                        {
                            Id = 5,
                            BiereId = 5,
                            GrossisteId = 1,
                            Quantite = 30
                        },
                        new
                        {
                            Id = 6,
                            BiereId = 1,
                            GrossisteId = 2,
                            Quantite = 10
                        },
                        new
                        {
                            Id = 7,
                            BiereId = 3,
                            GrossisteId = 2,
                            Quantite = 10
                        },
                        new
                        {
                            Id = 8,
                            BiereId = 4,
                            GrossisteId = 1,
                            Quantite = 10
                        });
                });

            modelBuilder.Entity("Brasserie.Core.Domain.Biere", b =>
                {
                    b.HasOne("Brasserie.Core.Domain.Brasserie", "Brasserie")
                        .WithMany("Bieres")
                        .HasForeignKey("BrasserieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Brasserie.Core.Domain.StockGrossiste", b =>
                {
                    b.HasOne("Brasserie.Core.Domain.Biere", "Biere")
                        .WithMany("StockGrossistes")
                        .HasForeignKey("BiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brasserie.Core.Domain.Grossiste", "Grossiste")
                        .WithMany("StockGrossistes")
                        .HasForeignKey("GrossisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
